# Generated by Django 4.0.4 on 2022-05-16 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runki', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
